version: '3'

name: 'clone-whatsapp-dev'

services:
  database:
    container_name: 'database-mongo'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
