export const ERR_DB_MIN_4_CHARACTERS = 'ERR_DB_MIN_4_CHARACTERS';
export const ERR_DB_MIN_6_CHARACTERS = 'ERR_DB_MIN_6_CHARACTERS';
export const ERR_DB_MIN_8_CHARACTERS = 'ERR_DB_MIN_8_CHARACTERS';

export const ERR_DB_MAX_32_CHARACTERS = 'ERR_DB_MAX_32_CHARACTERS';
export const ERR_DB_MAX_256_CHARACTERS = 'ERR_DB_MAX_256_CHARACTERS';

export const ERR_DB_ONLY_ALPHANUMERIC = 'ERR_DB_ONLY_ALPHANUMERIC';
export const ERR_DB_FIRST_CHAR_LETTER = 'ERR_DB_FIRST_CHAR_LETTER';
